# Generated by Django 4.0.6 on 2022-08-14 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('currency_code', models.CharField(max_length=3)),
                ('dialing_code', models.IntegerField()),
                ('continent', models.CharField(max_length=10)),
                ('country_name', models.CharField(default='None', max_length=50)),
                ('timezone', models.CharField(default='None', max_length=15)),
                ('alt_name', models.CharField(default='None', max_length=100)),
            ],
        ),
    ]
