# Generated by Django 4.0.6 on 2022-08-16 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name_plural': 'Cities'},
        ),
        migrations.AddField(
            model_name='city',
            name='country_code',
            field=models.CharField(default=' ', max_length=3),
        ),
        migrations.AddField(
            model_name='city',
            name='humidity',
            field=models.CharField(default=' ', max_length=10),
        ),
        migrations.AddField(
            model_name='city',
            name='icon',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AddField(
            model_name='city',
            name='pressure',
            field=models.CharField(default=' ', max_length=10),
        ),
        migrations.AddField(
            model_name='city',
            name='temperature',
            field=models.CharField(default=' ', max_length=6),
        ),
        migrations.AlterField(
            model_name='city',
            name='alt_name',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AlterField(
            model_name='city',
            name='country_name',
            field=models.CharField(default=' ', max_length=50),
        ),
        migrations.AlterField(
            model_name='city',
            name='timezone',
            field=models.CharField(default=' ', max_length=15),
        ),
    ]
