# Generated by Django 4.0.5 on 2022-10-01 20:55

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rating', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['rating'],
            },
        ),
        migrations.CreateModel(
            name='comment',
            fields=[
                ('Comment', models.CharField(max_length=200)),
                ('comment_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('no_of_likes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_user', models.IntegerField()),
                ('profileimg', models.ImageField(default='blank-profile-picture.png', upload_to='profile_images')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(default='', max_length=150)),
                ('pub_date', models.DateField()),
                ('rating', models.IntegerField(default=0)),
                ('views', models.IntegerField(default=0)),
                ('book', models.FileField(upload_to='books')),
                ('thumbnail', models.ImageField(upload_to='thumbnails')),
                ('uploaded_by', models.CharField(default='Anonymous', max_length=100)),
                ('time_added', models.DateTimeField(default=datetime.datetime.now)),
                ('category', models.CharField(default=False, max_length=100)),
                ('language', models.CharField(default=False, max_length=100)),
                ('press', models.CharField(default=False, max_length=150)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reeder.author')),
                ('comment', models.ManyToManyField(to='reeder.comment')),
            ],
            options={
                'ordering': ['rating'],
            },
        ),
    ]
