# Generated by Django 4.0.5 on 2022-10-01 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reeder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
