# Generated by Django 4.0.5 on 2022-10-01 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reeder', '0003_alter_book_category_alter_book_language_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='rating',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='book',
            name='comment',
            field=models.ManyToManyField(blank=True, to='reeder.comment'),
        ),
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='book',
            name='press',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='book',
            name='rating',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='uploaded_by',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='book',
            name='views',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='no_of_likes',
            field=models.IntegerField(),
        ),
    ]
