# Generated by Django 4.0.5 on 2022-10-01 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reeder', '0004_alter_author_rating_alter_book_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='page_number',
            field=models.IntegerField(default=False),
        ),
    ]
