# Generated by Django 4.0.5 on 2022-10-01 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reeder', '0005_book_page_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='page_number',
            field=models.IntegerField(),
        ),
    ]
